window.LISTINGS_DATA = [
  {
    "id": "104-paul-avenue",
    "status": "Active",
    "featured": true,
    "featuredOrder": 1,
    "community": "Weirton",
    "summary": "A versatile three-bedroom property with a rear dwelling, detached garage, deck, and flexible living options.",
    "address": "104 Paul Avenue",
    "cityStateZip": "Weirton, WV 26062",
    "price": "$214,000",
    "beds": 3,
    "baths": 2,
    "sqft": "1,060",
    "mls": "5209131",
    "image": "assets/104-paul-avenue/hero.jpg",
    "page": "property-showcase.html",
    "type": "Residential"
  },
  {
    "id": "333-patricia-avenue",
    "status": "Active",
    "featured": true,
    "featuredOrder": 2,
    "community": "Weirton",
    "summary": "A well-maintained split-level home with three bedrooms, one and a half baths, a large rear deck, and exceptional garage space.",
    "address": "333 Patricia Avenue",
    "cityStateZip": "Weirton, WV",
    "price": "Contact for Price",
    "beds": 3,
    "baths": 1.5,
    "sqft": "\u2014",
    "mls": "Contact Dante",
    "image": "assets/333-patricia-avenue/hero.jpg",
    "page": "333-patricia-avenue.html",
    "type": "Residential"
  },
  {
    "id": "listing-3",
    "status": "Coming Soon",
    "featured": true,
    "featuredOrder": 3,
    "community": "Ohio Valley",
    "summary": "Verified property information and media can be added here when this listing is ready.",
    "address": "Listing 3 \u2014 Add Address",
    "cityStateZip": "Ohio Valley",
    "price": "Price Coming Soon",
    "beds": "\u2014",
    "baths": "\u2014",
    "sqft": "\u2014",
    "mls": "Add MLS",
    "image": "assets/media-fallback.svg",
    "page": "#contact",
    "type": "Residential",
    "placeholder": true
  },
  {
    "id": "listing-4",
    "status": "Coming Soon",
    "featured": false,
    "featuredOrder": 4,
    "community": "Ohio Valley",
    "summary": "Verified property information and media can be added here when this listing is ready.",
    "address": "Listing 4 \u2014 Add Address",
    "cityStateZip": "Ohio Valley",
    "price": "Price Coming Soon",
    "beds": "\u2014",
    "baths": "\u2014",
    "sqft": "\u2014",
    "mls": "Add MLS",
    "image": "assets/media-fallback.svg",
    "page": "#contact",
    "type": "Residential",
    "placeholder": true
  },
  {
    "id": "listing-5",
    "status": "Coming Soon",
    "featured": false,
    "featuredOrder": 5,
    "community": "Ohio Valley",
    "summary": "Verified property information and media can be added here when this listing is ready.",
    "address": "Listing 5 \u2014 Add Address",
    "cityStateZip": "Ohio Valley",
    "price": "Price Coming Soon",
    "beds": "\u2014",
    "baths": "\u2014",
    "sqft": "\u2014",
    "mls": "Add MLS",
    "image": "assets/media-fallback.svg",
    "page": "#contact",
    "type": "Residential",
    "placeholder": true
  },
  {
    "id": "listing-6",
    "status": "Coming Soon",
    "featured": false,
    "featuredOrder": 6,
    "community": "Ohio Valley",
    "summary": "Verified property information and media can be added here when this listing is ready.",
    "address": "Listing 6 \u2014 Add Address",
    "cityStateZip": "Ohio Valley",
    "price": "Price Coming Soon",
    "beds": "\u2014",
    "baths": "\u2014",
    "sqft": "\u2014",
    "mls": "Add MLS",
    "image": "assets/media-fallback.svg",
    "page": "#contact",
    "type": "Residential",
    "placeholder": true
  },
  {
    "id": "listing-7",
    "status": "Coming Soon",
    "featured": false,
    "featuredOrder": 7,
    "community": "Ohio Valley",
    "summary": "Verified property information and media can be added here when this listing is ready.",
    "address": "Listing 7 \u2014 Add Address",
    "cityStateZip": "Ohio Valley",
    "price": "Price Coming Soon",
    "beds": "\u2014",
    "baths": "\u2014",
    "sqft": "\u2014",
    "mls": "Add MLS",
    "image": "assets/media-fallback.svg",
    "page": "#contact",
    "type": "Residential",
    "placeholder": true
  }
];
